### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by philippb** [KeepSafe/ks-email-parser#10]
when some XML is wrongly formatted we get this error

```
Traceback (most recent call last):
  File "/Users/philipp/coding/ks-email-parser/venv/bin/ks-email-parser", line 9, in <module>
    load_entry_point('ks-email-parser==0.2.2', 'console_scripts', 'ks-email-parser')()
  File "/Users/philipp/coding/ks-email-parser/venv/lib/python3.4/site-packages/ks_email_parser-0.2.2-py3.4.egg/email_parser/__init__.py", line 64, in main
  File "/Users/philipp/coding/ks-email-parser/venv/lib/python3.4/site-packages/ks_email_parser-0.2.2-py3.4.egg/email_parser/__init__.py", line 26, in parse_emails
  File "/Users/philipp/coding/ks-email-parser/venv/lib/python3.4/site-packages/ks_email_parser-0.2.2-py3.4.egg/email_parser/renderer.py", line 157, in render
  File "/Users/philipp/coding/ks-email-parser/venv/lib/python3.4/site-packages/ks_email_parser-0.2.2-py3.4.egg/email_parser/renderer.py", line 115, in render
  File "/Users/philipp/coding/ks-email-parser/venv/lib/python3.4/site-packages/ks_email_parser-0.2.2-py3.4.egg/email_parser/renderer.py", line 115, in <dictcomp>
  File "/Users/philipp/coding/ks-email-parser/venv/lib/python3.4/site-packages/ks_email_parser-0.2.2-py3.4.egg/email_parser/renderer.py", line 97, in _render_placeholder
  File "/Users/philipp/coding/ks-email-parser/venv/lib/python3.4/site-packages/ks_email_parser-0.2.2-py3.4.egg/email_parser/renderer.py", line 74, in _inline_css
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/xml/etree/ElementTree.py", line 1325, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 18, column 13
```

Something that indicates what XML file and maybe line would be good.

**Comment by ca77y** [comment]
fixed in #15
