### ISSUE TITLE
Formating validator report

### ISSUE THREAD

**Issue by philippb** [KeepSafe/ks-email-parser#17]
there should be a option that runs the content validator and creates a report for all emails in one HTML file that show wrong formatting and missing markdown items in an overview.

**Comment by snejku** [comment]
New sample output
```
$ ks-email-parser
F.....
ERRORS:
1. Unable to read content from /Users/snejku/keepsafe/ks-email-parser/src/en/email.xml
not well-formed (invalid token): line 5, column 28
Segment ID: content
_______________
    <string name="content"><<Dummy content</string>
                            ^
Traceback (most recent call last):
  File "/Users/snejku/keepsafe/ks-email-parser/venv/lib/python3.4/site-packages/ks_email_parser-0.2.6-py3.4.egg/email_parser/reader.py", line 67, in read
    tree = ElementTree.parse(email_path)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/xml/etree/ElementTree.py", line 1186, in parse
    tree.parse(source, parser)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/xml/etree/ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 5, column 28

All done
```
