### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by philippb** [KeepSafe/ks-email-parser#4]
We need better error messages on the console when something is not working. Something that we can do something about without reading code

e.g. this is shit
```
Parsing emails...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/ks-email-parser", line 9, in <module>
    load_entry_point('email-localization==0.0.1', 'console_scripts', 'ks-email-parser')()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/email_localization-0.0.1-py3.4.egg/email_parser.py", line 294, in main
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/email_localization-0.0.1-py3.4.egg/email_parser.py", line 253, in parse_emails
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/email_localization-0.0.1-py3.4.egg/email_parser.py", line 239, in save_email_content_as_html
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/email_localization-0.0.1-py3.4.egg/email_parser.py", line 146, in to_html
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/email_localization-0.0.1-py3.4.egg/email_parser.py", line 132, in content_to_html
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/email_localization-0.0.1-py3.4.egg/email_parser.py", line 141, in _inline_css
TypeError: 'NoneType' object is not iterable
```

**Comment by ca77y** [comment]
should not happen any more
